"""New features

Revision ID: 3c4e8ee64be4
Revises: 078f9980fdaa
Create Date: 2017-02-13 10:46:27.827593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4e8ee64be4'
down_revision = '078f9980fdaa'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circles', sa.Column('bottom_line', sa.Unicode(), nullable=True))
    op.add_column('circles', sa.Column('can_join', sa.Boolean(), nullable=False, default=True, server_default=sa.text('true')))
    op.add_column('circles', sa.Column('join_code', sa.Unicode(), nullable=True))
    op.add_column('moments', sa.Column('reminder_time', sa.Time(), nullable=True))
    op.alter_column('statements', 'value', new_column_name='comment')
    op.add_column('users', sa.Column('loud', sa.Boolean(), nullable=False, default=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('reminder', sa.Boolean(), nullable=False, default=False, server_default=sa.text('false')))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reminder')
    op.drop_column('users', 'loud')
    op.alter_column('statements', 'comment', new_column_name='value')
    op.drop_column('moments', 'reminder_time')
    op.drop_column('circles', 'join_code')
    op.drop_column('circles', 'can_join')
    op.drop_column('circles', 'bottom_line')
    ### end Alembic commands ###
